[package]
name = "vigenere"
version = "0.1.0"
authors = ["Jonatan Ojala <jojala@igpte.ch>"]
edition = "2018"
publish = false

[profile.release]
lto = true

[profile.bench]
lto = true

# This is to allow `cargo test` to run
[dev-dependencies]
wee_alloc = "0.4.4"