[package]
name = "base64-bruteforce"
version = "0.1.0"
authors = ["Jonatan Ojala <jojala@igpte.ch>"]
edition = "2018"


[profile.release]
lto = "fat"

[profile.bench]
lto = "fat"


[dependencies]
time = "0.1.42"
vigenere = {path = "../../"}
vigenere-base64 = {path = "../../vigenere-base64/"}
